spring.application.name=rumi_backend_v2
spring.autoconfigure.exclude=org.springframework.ai.model.azure.openai.autoconfigure.AzureOpenAiChatAutoConfiguration,org.springframework.ai.model.azure.openai.autoconfigure.AzureOpenAiEmbeddingAutoConfiguration,org.springframework.ai.model.azure.openai.autoconfigure.AzureOpenAiImageAutoConfiguration,org.springframework.ai.model.azure.openai.autoconfigure.AzureOpenAiAudioTranscriptionAutoConfiguration,org.springframework.ai.model.openai.autoconfigure.OpenAiChatAutoConfiguration,org.springframework.ai.model.openai.autoconfigure.OpenAiEmbeddingAutoConfiguration,org.springframework.ai.model.openai.autoconfigure.OpenAiImageAutoConfiguration,org.springframework.ai.model.openai.autoconfigure.OpenAiAudioSpeechAutoConfiguration,org.springframework.ai.model.openai.autoconfigure.OpenAiAudioTranscriptionAutoConfiguration,org.springframework.ai.model.openai.autoconfigure.OpenAiModerationAutoConfiguration,org.springframework.ai.model.chat.memory.repository.cosmosdb.autoconfigure.CosmosDBChatMemoryRepositoryAutoConfiguration,org.springframework.ai.vectorstore.azure.autoconfigure.AzureVectorStoreAutoConfiguration

# MySQL connection
spring.datasource.url=${DB_URL}/rumi_rental_db
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA & Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

#Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration