/* ── Shared mock room data for RUMI ── */
export const mockRooms = [
  {
    id: 1,
    title: 'Modern Studio Apartment',
    location: 'Colombo 3, Western Province',
    city: 'Colombo',
    lat: 6.9021,
    lng: 79.8558,
    price: 45000,
    type: 'Studio',
    bedrooms: 1,
    bathrooms: 1,
    sqft: 380,
    rating: 4.8,
    reviews: 24,
    available: true,
    landlord: { name: 'Kasun Perera', joined: '2023' },
    amenities: ['WiFi', 'Air Conditioning', 'Hot Water', 'Parking', 'Security', 'Furnished'],
    rules: ['No smoking', 'No pets', 'Quiet hours after 10 pm'],
    description:
      'A beautifully furnished modern studio in the heart of Colombo 3. Ideal for young professionals. The apartment is fully air-conditioned with high-speed fibre WiFi and 24-hour security. Walking distance to supermarkets, cafés, and the Beira Lake promenade.',
    images: [
      'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=900',
      'https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
  },
  {
    id: 2,
    title: '2BR Apartment — Sea View',
    location: 'Beach Road, Negombo',
    city: 'Negombo',
    lat: 7.2095,
    lng: 79.8353,
    price: 85000,
    type: 'Apartment',
    bedrooms: 2,
    bathrooms: 2,
    sqft: 750,
    rating: 4.6,
    reviews: 18,
    available: true,
    landlord: { name: 'Nimal Silva', joined: '2022' },
    amenities: ['WiFi', 'Air Conditioning', 'Sea View', 'Balcony', 'Parking', 'Security'],
    rules: ['No smoking', 'No loud music after 9 pm'],
    description:
      'Spacious 2-bedroom apartment with breathtaking sea views from the balcony. Located steps from Negombo beach, this apartment is perfect for families or couples who love the ocean lifestyle. Both bedrooms have their own A/C units.',
    images: [
      'https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=900',
      'https://images.pexels.com/photos/1454806/pexels-photo-1454806.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
  },
  {
    id: 3,
    title: 'Cozy Annex — Kandy Hillside',
    location: 'Kandy City, Central Province',
    city: 'Kandy',
    lat: 7.2906,
    lng: 80.6337,
    price: 35000,
    type: 'Annex',
    bedrooms: 1,
    bathrooms: 1,
    sqft: 420,
    rating: 4.9,
    reviews: 31,
    available: true,
    landlord: { name: 'Amali Fernando', joined: '2024' },
    amenities: ['WiFi', 'Hot Water', 'Garden', 'Quiet', 'Furnished'],
    rules: ['No smoking inside', 'No pets'],
    description:
      'A peaceful, well-maintained annex nestled in a lush Kandy hillside garden. Enjoy cool weather, mountain views, and a private garden. Ideal for someone seeking a calm retreat close to the Kandy city centre. The property is fully furnished.',
    images: [
      'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=900',
      'https://images.pexels.com/photos/1457847/pexels-photo-1457847.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
  },
  {
    id: 4,
    title: 'Spacious 3BR Family House',
    location: 'Galle Fort Area, Southern Province',
    city: 'Galle',
    lat: 6.0535,
    lng: 80.2210,
    price: 130000,
    type: 'House',
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1400,
    rating: 4.7,
    reviews: 12,
    available: false,
    landlord: { name: 'Sachini Dias', joined: '2021' },
    amenities: ['WiFi', 'Air Conditioning', 'Garden', 'Parking', 'Generator', 'Security'],
    rules: ['No smoking', 'No parties', 'Quiet hours after 10 pm'],
    description:
      'A beautifully maintained 3-bedroom house near the iconic Galle Fort. Features a private garden, dedicated parking, and a backup generator. Perfect for families relocating or expats seeking a long-term rental in the charming Galle setting.',
    images: [
      'https://images.pexels.com/photos/1396122/pexels-photo-1396122.jpeg?auto=compress&cs=tinysrgb&w=900',
      'https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
  },
  {
    id: 5,
    title: 'Student Boarding Room',
    location: 'Colombo 5, Western Province',
    city: 'Colombo',
    lat: 6.8936,
    lng: 79.8584,
    price: 18000,
    type: 'Boarding',
    bedrooms: 1,
    bathrooms: 1,
    sqft: 200,
    rating: 4.3,
    reviews: 47,
    available: true,
    landlord: { name: 'Ruwan Gayan', joined: '2022' },
    amenities: ['WiFi', 'Shared Kitchen', 'Common Area', 'Security'],
    rules: ['No smoking', 'No guests after 9 pm'],
    description:
      'Affordable and secure boarding room ideal for students and young working professionals. Shared kitchen and common areas are well maintained. Located near public transport links, universities, and cafés.',
    images: [
      'https://images.pexels.com/photos/271624/pexels-photo-271624.jpeg?auto=compress&cs=tinysrgb&w=900',
      'https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
  },
  {
    id: 6,
    title: 'Executive Apartment — Colombo 7',
    location: 'Colombo 7, Western Province',
    city: 'Colombo',
    lat: 6.9100,
    lng: 79.8650,
    price: 180000,
    type: 'Apartment',
    bedrooms: 3,
    bathrooms: 2,
    sqft: 1100,
    rating: 4.9,
    reviews: 9,
    available: true,
    landlord: { name: 'Ishara Madhu', joined: '2023' },
    amenities: ['WiFi', 'Air Conditioning', 'Gym', 'Pool', 'Parking', 'Security', 'Furnished'],
    rules: ['No smoking', 'No pets', 'Quiet hours after 10 pm'],
    description:
      'Luxury executive apartment in the most prestigious neighbourhood of Colombo. Features a fully-equipped kitchen, premium furnishings, access to a rooftop pool, gym, and 24-hour concierge service. Ideal for senior executives or diplomats.',
    images: [
      'https://images.pexels.com/photos/2440471/pexels-photo-2440471.jpeg?auto=compress&cs=tinysrgb&w=900',
      'https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg?auto=compress&cs=tinysrgb&w=600',
      'https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg?auto=compress&cs=tinysrgb&w=600',
    ],
  },
];
