name: CI Pipeline

on:
  push:
    branches: ["kavin-dev"]
  pull_request:
    branches: ["kavin-dev"]

jobs:

  # frontend (React)
  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: my-app  #get the frontend directory

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install  # the exact dependency from the package-lock.js

      - name: Run tests
        run: npm run test:ci

      - name: Build project
        run: npm run build


  # Backend (Spring Boot)
  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: rumi_backend_v2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 24
          distribution: temurin

      - name: Make Maven wrapper executable
        run: chmod +x ./mvnw

      - name: Build project
        run: ./mvnw clean install

      - name: Run tests
        run: ./mvnw test
