#The Ubuntu-latest test the spring and frontend application by only compiling,running,tests and packaging
# It is not running our Spring boot application so it won't search for the Supabase credentials.
# CI/CD only compile and run the test file.
name: CI Pipeline

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  # frontend (React)
  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: my-app  #get the frontend directory

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # pull the repo into the runner

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install  

      # - name: Run tests
      #   run: npm run test:ci

      - name: Build project
        run: CI=false npm run build


  # Backend (Spring Boot)
  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: rumi_backend_v2

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Make Maven wrapper executable
        run: chmod +x ./mvnw

      - name: Build project
        run: ./mvnw clean install  # Compiles + runs tests + packages app

#      - name: Run tests
#        run: ./mvnw test
